// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geirzyjdfcqbmcmlyhex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaXJ6eWpkZmNxYm1jbWx5aGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTE5NjksImV4cCI6MjA2OTk4Nzk2OX0.WqHX5Y4c6hzKNHDRVlS01ehxm2IzZ_I6cnXo6rPdfyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});